from __future__ import annotations

import json
import subprocess
import sys
from copy import deepcopy
from pathlib import Path

import pytest
import tomllib
import yaml

from tools.verify_dependency_audit import (
    BASELINE_ENV,
    BASELINE_EXPRESSION,
    CACHE_PATH,
    CHECKOUT_ACTION,
    CHECKOUT_STEP,
    EXECUTE_STEP,
    FULL_TEST_STEP,
    INITIAL_REQUIREMENTS,
    INSTALL_COMMAND,
    INSTALL_STEP,
    OUTPUT_PATH,
    PREPARE_STEP,
    VALIDATE_STEP,
    DependencyAuditError,
    audit_command,
    execute_policy,
    executor_command,
    lock_inventory,
    policy_from_git,
    validate_policy,
    validate_workflow,
    validator_command,
    verify_report,
)

ROOT = Path(__file__).resolve().parents[1]
POLICY = ROOT / "quality-dependency-audit.toml"
WORKFLOW = ROOT / ".github" / "workflows" / "qa.yml"


def _policy():
    return tomllib.loads(POLICY.read_text(encoding="utf-8"))


def _workflow():
    return yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))


def _workflow_text(workflow) -> str:
    return yaml.safe_dump(workflow, sort_keys=False)


def _step(workflow, name: str):
    return next(step for step in workflow["jobs"]["test"]["steps"] if step["name"] == name)


def _write_lock(path: Path, rows: list[tuple[str, str]]) -> None:
    body = [
        "# This file is autogenerated by pip-compile with Python 3.13",
        "# --generate-hashes",
    ]
    for index, (name, version) in enumerate(rows, start=1):
        body.extend(
            (
                f"{name}=={version} \\",
                f"    --hash=sha256:{index:064x}",
            )
        )
    path.write_text("\n".join(body) + "\n", encoding="utf-8")


def _write_policy(path: Path, requirements: tuple[str, ...] = INITIAL_REQUIREMENTS) -> None:
    rows = "\n".join(f'    "{item}",' for item in requirements)
    path.write_text(
        "schema_version = 1\n\n"
        "[audit]\n"
        "requirements = [\n"
        f"{rows}\n"
        "]\n"
        'vulnerability_service = "pypi"\n'
        "strict = true\n"
        "require_hashes = true\n"
        "disable_pip = true\n"
        "python_isolated = true\n"
        'progress_spinner = "off"\n'
        'format = "json"\n'
        'descriptions = "off"\n'
        'aliases = "on"\n'
        "timeout_seconds = 15\n"
        f'output_path = "{OUTPUT_PATH}"\n'
        f'cache_path = "{CACHE_PATH}"\n'
        "ignored_vulnerabilities = []\n",
        encoding="utf-8",
    )


def _temporary_repository(tmp_path: Path) -> tuple[Path, Path]:
    repository = tmp_path / "repository"
    repository.mkdir()
    _write_lock(
        repository / "requirements-dev.txt",
        [("alpha_pkg", "1.0"), ("shared.pkg", "2.0")],
    )
    _write_lock(
        repository / "requirements-build.txt",
        [("shared-pkg", "2.0"), ("bravo", "3.0")],
    )
    (repository / "qa-artifacts").mkdir()
    policy_path = repository / POLICY.name
    _write_policy(policy_path)
    return repository, policy_path


def _clean_report(inventory: dict[str, str]) -> dict[str, object]:
    return {
        "dependencies": [
            {"name": name, "version": version, "vulns": []}
            for name, version in inventory.items()
        ],
        "fixes": [],
    }


def test_live_policy_workflow_command_and_lock_union_pass():
    policy = _policy()
    validate_policy(policy, ROOT)
    validate_workflow(WORKFLOW.read_text(encoding="utf-8"))
    inventory = lock_inventory(policy["audit"]["requirements"], ROOT)
    command = audit_command(policy, ROOT)

    assert command[:4] == [sys.executable, "-I", "-m", "pip_audit"]
    assert command.count("-r") == 2
    assert [command[index + 1] for index, value in enumerate(command) if value == "-r"] == list(
        INITIAL_REQUIREMENTS
    )
    for token in (
        "--strict",
        "--require-hashes",
        "--disable-pip",
        "--vulnerability-service",
        "pypi",
        "--format",
        "json",
        "--desc",
        "off",
        "--aliases",
        "on",
    ):
        assert token in command
    assert not {"--ignore-vuln", "--fix", "--dry-run", "--no-deps"} & set(command)
    assert {"numpy", "streamlit", "pyinstaller", "mypy", "pip-audit"} <= set(inventory)
    assert validator_command().endswith(
        "--baseline-ref $env:SECTOR_DEPENDENCY_AUDIT_BASE"
    )
    assert executor_command().endswith("--execute")


def test_execute_policy_sanitises_environment_and_verifies_complete_report(
    tmp_path,
    monkeypatch,
):
    repository, policy_path = _temporary_repository(tmp_path)
    inventory = lock_inventory(INITIAL_REQUIREMENTS, repository)
    observed = {}
    monkeypatch.setenv("PYTHONPATH", "shadow")
    monkeypatch.setenv("PYTHONHOME", "shadow")
    monkeypatch.setenv("PIP_INDEX_URL", "https://example.invalid/simple")
    monkeypatch.setenv("PIP_AUDIT_OSV_URL", "https://example.invalid/query")

    def runner(command, **kwargs):
        observed["command"] = command
        observed["env"] = kwargs["env"]
        (repository / OUTPUT_PATH).write_text(
            json.dumps(_clean_report(inventory)),
            encoding="utf-8",
        )
        return subprocess.CompletedProcess(command, 0, "", "No known vulnerabilities\n")

    execute_policy(policy_path, repository, runner=runner)

    assert observed["command"][:4] == [sys.executable, "-I", "-m", "pip_audit"]
    assert "PYTHONPATH" not in observed["env"]
    assert "PYTHONHOME" not in observed["env"]
    assert not any(name.startswith("PIP_") for name in observed["env"])
    assert observed["env"]["PYTHONNOUSERSITE"] == "1"
    assert observed["env"]["PYTHONSAFEPATH"] == "1"


def test_subprocess_failure_and_existing_evidence_fail_closed(tmp_path):
    repository, policy_path = _temporary_repository(tmp_path)

    def failing(command, **kwargs):
        return subprocess.CompletedProcess(command, 1, "", "known vulnerability")

    with pytest.raises(DependencyAuditError, match="exit code 1"):
        execute_policy(policy_path, repository, runner=failing)

    (repository / OUTPUT_PATH).write_text("{}", encoding="utf-8")
    with pytest.raises(DependencyAuditError, match="already exists"):
        execute_policy(policy_path, repository, runner=failing)


@pytest.mark.parametrize(
    ("case", "message"),
    [
        ("missing", "inventory differs"),
        ("extra", "inventory differs"),
        ("changed", "inventory differs"),
        ("duplicate", "duplicate dependency"),
        ("skipped", "skipped, unknown or malformed"),
        ("vulnerable", "known vulnerability"),
        ("fix", "must not contain fix"),
        ("unknown_row_key", "skipped, unknown or malformed"),
        ("unknown_top_key", "report keys differ"),
    ],
)
def test_report_inventory_and_vulnerability_bypasses_fail(tmp_path, case, message):
    expected = {"alpha-pkg": "1.0", "bravo": "2.0"}
    report = _clean_report(expected)
    rows = report["dependencies"]
    if case == "missing":
        rows.pop()
    elif case == "extra":
        rows.append({"name": "charlie", "version": "3.0", "vulns": []})
    elif case == "changed":
        rows[0]["version"] = "9.0"
    elif case == "duplicate":
        rows.append(deepcopy(rows[0]))
    elif case == "skipped":
        rows[0] = {"name": "alpha-pkg", "skip_reason": "unresolved"}
    elif case == "vulnerable":
        rows[0]["vulns"] = [{"id": "PYSEC-1"}]
    elif case == "fix":
        report["fixes"] = [{"name": "alpha-pkg"}]
    elif case == "unknown_row_key":
        rows[0]["ignored"] = True
    elif case == "unknown_top_key":
        report["ignored"] = []
    path = tmp_path / "audit.json"
    path.write_text(json.dumps(report), encoding="utf-8")

    with pytest.raises(DependencyAuditError, match=message):
        verify_report(path, expected)


def test_lock_inventory_rejects_unhashed_unpinned_duplicate_and_conflicting_rows(
    tmp_path,
):
    repository, _ = _temporary_repository(tmp_path)
    dev = repository / "requirements-dev.txt"
    build = repository / "requirements-build.txt"

    dev.write_text("alpha==1.0\n", encoding="utf-8")
    with pytest.raises(DependencyAuditError, match="unhashed"):
        lock_inventory(INITIAL_REQUIREMENTS, repository)

    dev.write_text("alpha>=1.0\n", encoding="utf-8")
    with pytest.raises(DependencyAuditError, match="non-exact"):
        lock_inventory(INITIAL_REQUIREMENTS, repository)

    _write_lock(dev, [("alpha", "1.0"), ("alpha", "1.0")])
    with pytest.raises(DependencyAuditError, match="duplicate requirement"):
        lock_inventory(INITIAL_REQUIREMENTS, repository)

    _write_lock(dev, [("shared", "1.0")])
    _write_lock(build, [("shared", "2.0")])
    with pytest.raises(DependencyAuditError, match="conflicting audited versions"):
        lock_inventory(INITIAL_REQUIREMENTS, repository)


@pytest.mark.parametrize(
    ("text", "message"),
    [
        ("--index-url https://example.invalid/simple\n", "unsupported lock control"),
        ("--trusted-host example.invalid\n", "unsupported lock control"),
        (
            "alpha==1.0 \\\n    --hash=sha256:not-a-hash\n",
            "malformed requirement hash",
        ),
        ("# generated but empty\n", "audit requirement is empty"),
    ],
)
def test_lock_inventory_rejects_controls_malformed_hashes_and_empty_locks(
    tmp_path,
    text,
    message,
):
    repository, _ = _temporary_repository(tmp_path)
    (repository / "requirements-dev.txt").write_text(text, encoding="utf-8")

    with pytest.raises(DependencyAuditError, match=message):
        lock_inventory(INITIAL_REQUIREMENTS, repository)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("vulnerability_service", "osv"),
        ("strict", False),
        ("require_hashes", False),
        ("disable_pip", False),
        ("python_isolated", False),
        ("progress_spinner", "on"),
        ("format", "columns"),
        ("descriptions", "on"),
        ("aliases", "off"),
        ("timeout_seconds", 0),
        ("ignored_vulnerabilities", ["PYSEC-1"]),
    ],
)
def test_weaker_or_unadvertised_audit_settings_are_rejected(field, value):
    policy = deepcopy(_policy())
    policy["audit"][field] = value

    with pytest.raises(DependencyAuditError, match=field):
        validate_policy(policy, ROOT)


def test_lock_identity_duplicates_and_escaping_paths_are_rejected(tmp_path):
    policy = deepcopy(_policy())
    policy["audit"]["requirements"].reverse()
    with pytest.raises(DependencyAuditError, match="identity or order"):
        validate_policy(policy, ROOT)

    policy = deepcopy(_policy())
    policy["audit"]["requirements"].append(INITIAL_REQUIREMENTS[0])
    with pytest.raises(DependencyAuditError, match="duplicates"):
        validate_policy(policy, ROOT)

    repository = tmp_path / "repository"
    repository.mkdir()
    policy = deepcopy(_policy())
    policy["audit"]["requirements"][0] = "../outside.txt"
    with pytest.raises(DependencyAuditError, match="escapes the repository"):
        validate_policy(policy, repository)


def test_accepted_lock_inventory_can_append_but_cannot_shrink_or_reorder(tmp_path):
    repository, policy_path = _temporary_repository(tmp_path)
    baseline = tomllib.loads(policy_path.read_text(encoding="utf-8"))
    _write_lock(repository / "requirements-release.txt", [("release", "1.0")])
    _write_lock(repository / "requirements-export.txt", [("export", "1.0")])
    candidate = deepcopy(baseline)
    candidate["audit"]["requirements"].extend(
        ("requirements-release.txt", "requirements-export.txt")
    )

    validate_policy(candidate, repository, baseline=baseline)

    with pytest.raises(DependencyAuditError, match="inventory shrank"):
        validate_policy(baseline, repository, baseline=candidate)
    reordered = deepcopy(candidate)
    reordered["audit"]["requirements"][-2:] = reversed(
        reordered["audit"]["requirements"][-2:]
    )
    with pytest.raises(DependencyAuditError, match="exact candidate prefix"):
        validate_policy(reordered, repository, baseline=candidate)

    _write_lock(repository / "requirements-new.txt", [("new", "1.0")])
    inserted = deepcopy(candidate)
    inserted["audit"]["requirements"].insert(-2, "requirements-new.txt")
    with pytest.raises(DependencyAuditError, match="exact candidate prefix"):
        validate_policy(inserted, repository, baseline=candidate)


def test_policy_is_loaded_from_the_exact_git_base(tmp_path):
    repository = tmp_path / "repository"
    repository.mkdir()
    policy_path = repository / POLICY.name
    for command in (
        ["init"],
        ["config", "user.name", "Sector QA"],
        ["config", "user.email", "sector-qa@example.invalid"],
        ["commit", "--allow-empty", "-m", "base without audit policy"],
    ):
        subprocess.run(
            ["git", *command],
            cwd=repository,
            check=True,
            capture_output=True,
            text=True,
        )
    assert policy_from_git("HEAD", policy_path, repository) is None

    _write_lock(repository / "requirements-dev.txt", [("alpha", "1.0")])
    _write_lock(repository / "requirements-build.txt", [("bravo", "2.0")])
    _write_policy(policy_path)
    for command in (
        ["add", POLICY.name],
        ["commit", "-m", "accepted dependency audit policy"],
    ):
        subprocess.run(
            ["git", *command],
            cwd=repository,
            check=True,
            capture_output=True,
            text=True,
        )
    loaded = policy_from_git("HEAD", policy_path, repository)
    assert loaded is not None
    assert tuple(loaded["audit"]["requirements"]) == INITIAL_REQUIREMENTS
    with pytest.raises(DependencyAuditError, match="Git baseline inspection"):
        policy_from_git("missing-base", policy_path, repository)


@pytest.mark.parametrize("step_name", [VALIDATE_STEP, EXECUTE_STEP])
@pytest.mark.parametrize(
    ("field", "value"),
    [("if", "false"), ("continue-on-error", True), ("working-directory", "docs")],
)
def test_policy_steps_are_unconditional_and_failure_propagating(step_name, field, value):
    workflow = _workflow()
    _step(workflow, step_name)[field] = value

    with pytest.raises(DependencyAuditError, match="skipped or masked"):
        validate_workflow(_workflow_text(workflow))


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("if", "false"),
        ("continue-on-error", True),
        ("needs", "windows-package"),
        ("env", {"PIP_AUDIT_OSV_URL": "https://example.invalid"}),
    ],
)
def test_test_job_context_cannot_mask_the_audit(field, value):
    workflow = _workflow()
    workflow["jobs"]["test"][field] = value

    with pytest.raises(DependencyAuditError, match="test job execution context"):
        validate_workflow(_workflow_text(workflow))


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("name", "Optional audit"),
        ("runs-on", "ubuntu-latest"),
        ("timeout-minutes", 1),
    ],
)
def test_test_job_identity_cannot_disable_or_starve_the_audit(field, value):
    workflow = _workflow()
    workflow["jobs"]["test"][field] = value

    with pytest.raises(DependencyAuditError, match="test job execution identity"):
        validate_workflow(_workflow_text(workflow))


def test_checkout_install_baseline_triggers_commands_and_order_are_exact():
    workflow = _workflow()
    _step(workflow, CHECKOUT_STEP)["with"]["fetch-depth"] = 1
    with pytest.raises(DependencyAuditError, match="accepted Git baseline"):
        validate_workflow(_workflow_text(workflow))

    workflow = _workflow()
    _step(workflow, INSTALL_STEP)["run"] = "python -m pip install pip-audit"
    with pytest.raises(DependencyAuditError, match="locked QA install"):
        validate_workflow(_workflow_text(workflow))

    workflow = _workflow()
    _step(workflow, VALIDATE_STEP)["env"][BASELINE_ENV] = "HEAD^"
    with pytest.raises(DependencyAuditError, match="baseline expression"):
        validate_workflow(_workflow_text(workflow))

    workflow = _workflow()
    triggers = workflow.get("on", workflow.get(True))
    triggers["pull_request"] = {"paths": ["requirements*.txt"]}
    with pytest.raises(DependencyAuditError, match="unfiltered"):
        validate_workflow(_workflow_text(workflow))

    workflow = _workflow()
    steps = workflow["jobs"]["test"]["steps"]
    executor = steps.pop(steps.index(_step(workflow, EXECUTE_STEP)))
    steps.insert(steps.index(_step(workflow, FULL_TEST_STEP)) + 1, executor)
    with pytest.raises(DependencyAuditError, match="step order"):
        validate_workflow(_workflow_text(workflow))

    workflow = _workflow()
    assert _step(workflow, INSTALL_STEP)["run"] == INSTALL_COMMAND
    assert _step(workflow, VALIDATE_STEP)["env"] == {
        BASELINE_ENV: BASELINE_EXPRESSION
    }
    assert _step(workflow, CHECKOUT_STEP)["uses"] == CHECKOUT_ACTION
    assert _step(workflow, PREPARE_STEP)["shell"] == "pwsh"
