"""Guards for the pinned runtime, dependency locks and CI gate."""

from __future__ import annotations

import pathlib
import re

import pytest

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOCKS = (
    "requirements.txt",
    "requirements-dev.txt",
    "requirements-build.txt",
)


@pytest.mark.parametrize("filename", LOCKS)
def test_dependency_lock_is_generated_hashed_and_exact(filename):
    text = (ROOT / filename).read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.13" in text
    assert "--generate-hashes" in text

    requirement_lines = [
        line for line in text.splitlines()
        if line and not line.startswith((" ", "#", "-"))
    ]
    assert requirement_lines
    for line in requirement_lines:
        package = line.split(";", 1)[0].rstrip(" \\")
        assert re.match(r"^[A-Za-z0-9_.-]+==[^=<>!~]+$", package), line

    pinned = sum("==" in line for line in requirement_lines)
    hashes = text.count("--hash=sha256:")
    assert hashes >= pinned


def test_supported_python_runtime_is_pinned():
    assert (ROOT / ".python-version").read_text(encoding="ascii").strip() == "3.13.0"


def test_ci_runs_full_tests_artifact_renders_and_windows_build():
    workflow = (ROOT / ".github" / "workflows" / "qa.yml").read_text(
        encoding="utf-8"
    )
    assert "runs-on: windows-latest" in workflow
    assert "python -m pytest tests" in workflow
    assert "tools/report_render_fixture.py" in workflow
    assert "tools/manual_render_fixture.py" in workflow
    assert "python -m PyInstaller" in workflow
    assert workflow.count("--require-hashes") == 2
